server:
  port: 7777

spring:
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2DBDialect
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        show-sql: true


logging:
  level:
    org:
      hibernate: info