server:
  port: 7777


spring:
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/jhlog
    username: root
    password: kwic5539
    driver-class: org.mariadb.jdbc.Driver
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  output:
    ansi:
      enabled: ALWAYS

logging:
  level:
    org:
      hibernate: info